-- require("lualine").setup({
--   options = {
--     theme = "tokyonight",
--     -- ... the rest of your lualine config
--   },
--   -- sections = {
--   --   lualine_x = {
--   --     "copilot",
--   --   },
--   -- },
-- })
