-- local withPrettierd = function()
--   return {
--     exe = "prettierd",
--     args = {vim.api.nvim_buf_get_name(0)},
--     stdin = true
--   }
-- end
--
-- require('formatter').setup({
--   logging = true,
--   log_level = vim.log.levels.WARN,
--
--   filetype = {
--     javascript = withPrettierd,
--     typescript = withPrettierd,
--     javascriptreact = withPrettierd,
--     typescriptreact = withPrettierd,
--   },
-- })
--
-- local lspconfig = require('lspconfig')
--
-- local function organize_imports()
--   local params = {
--     command = "_typescript.organizeImports",
--     arguments = {vim.api.nvim_buf_get_name(0)},
--     title = ""
--   }
--   vim.lsp.buf.execute_command(params)
-- end
--
-- lspconfig.tsserver.setup {
--   commands = {
--     OrganizeImports = {
--       organize_imports,
--       description = "Organize Imports"
--     }
--   }
-- }
--
-- -- Format and organise on save 
-- local augroup = vim.api.nvim_create_augroup
-- local autocmd = vim.api.nvim_create_autocmd
-- augroup("__formatter__", { clear = true })
-- autocmd("BufWritePost", {
-- 	group = "__formatter__",
-- 	command = ":FormatWrite",
-- })
